name: proyecto_final
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  color: ^3.0.0
  google_sign_in: ^5.2.0
  equatable: ^2.0.3
  font_awesome_flutter: ^9.1.0
  auth_buttons: ^1.0.1+4
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  cloud_firestore: ^2.5.3
  flutter_bloc: ^7.3.1
  bloc: ^7.2.1
  sign_in_with_apple: ^3.2.0
  http: ^0.13.4
  platform: ^3.0.2
  image_picker: ^0.8.4+4
  firebase_storage: ^10.0.6
  firebase_storage_web: ^3.0.4
  native_pdf_view: ^5.0.0
  pdf: ^3.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_analytics: ^8.3.3

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/pinkgold.png
    - assets/images/loginBackground.jpg
    - assets/images/wp6707078.jpg
    - assets/images/appleLogin.png
    - assets/images/googleLogin.png
    - assets/images/py.png
    - assets/images/bad.png
    - assets/images/good.png
    - assets/images/check.png
    - assets/images/kendalljenner.jpg
    - assets/quizz/Python.json
